# Align PGOne NuGet MAUI package versions with the installed MAUI workload.
# Version mismatch is a common cause of BlazorWebView showing only a black screen.
Write-Host "Detecting installed MAUI workload version..." -ForegroundColor Cyan

$dotnet = if (Test-Path "C:\Program Files\dotnet\dotnet.exe") {
    "C:\Program Files\dotnet\dotnet.exe"
} else {
    (Get-Command dotnet -ErrorAction SilentlyContinue).Source
}

if (-not $dotnet) {
    Write-Host "ERROR: dotnet not found." -ForegroundColor Red
    exit 1
}

$workloads = & $dotnet workload list 2>&1 | Out-String
$match = [regex]::Match($workloads, 'maui[^\d]*(\d+\.\d+\.\d+)')
if (-not $match.Success) {
    Write-Host "WARNING: Could not detect MAUI workload version from 'dotnet workload list'." -ForegroundColor Yellow
    Write-Host "Install the workload: dotnet workload install maui"
    Write-Host "Then run this script again."
    exit 1
}

$version = $match.Groups[1].Value
$propsPath = Join-Path $PSScriptRoot "MauiVersion.local.props"
$content = @"
<Project>
  <!-- Auto-generated by sync-maui-version.ps1 -->
  <PropertyGroup>
    <MauiVersion>$version</MauiVersion>
  </PropertyGroup>
</Project>
"@

Set-Content -Path $propsPath -Value $content -Encoding UTF8
Write-Host "Wrote $propsPath with MauiVersion=$version" -ForegroundColor Green
Write-Host "Rebuild the app (clean + F5) for the change to take effect."
